package config

const (
	ENV_KEY_PORT        = "DATA_MANAGEMENT_PORT"
	ENV_KEY_JWT_SECRECT = "DATA_MANAGEMENT_SECRET"

	ENV_KEY_MONGO_SRV = "DATA_MONGO_SRV"
	ENV_KEY_MONGO_DB  = "DATA_MONGO_DB"

	ENV_KEY_MYSQL_DSN = "DATA_MYSQL_DSN"
)
